[rmkit] update remux to 0.1.4-1
matteodelabre/toltec pull request #171
Opened 2020-12-30 09:11 UTC by raisjn

* use genie gesture engine inside remux

to test this update, use remux and swipe up the sides of the screen to verify it still launches

2020-12-30 17:19 UTC, Eeems commented
Is it suppose to add a new package for genie as well? Or is it embedded?

2020-12-30 17:23 UTC, raisjn commented
it's embedded, but genie has a binary that exposes that engine (and unpaused still)

2021-01-01 01:01 UTC, Eeems requested changes
So it launches if I swipe up the right side of the screen. Is it also suppose to do so on the left side?

When I click the suspend button it appears to go back to xochitl and not suspend. Upon pressing any button the device powers off.

2021-01-01 02:38 UTC, Eeems approved these changes

2021-01-01 05:05 UTC, merged