util.auto_extract: Extract broken symlinks
matteodelabre/toltec pull request #302
Opened 2021-03-03 22:18 UTC by matteodelabre

Fixes #291.

Broken symlinks in source archives previously triggered build errors when auto-extracted. This PR changes this behavior to always create symlinks even if their destination does not (yet) exist.

Test plan:

* Make sure all other recipes still build (`make repo-local`)
* Build the following recipe:

```sh
pkgnames=(test-symlinks)
pkgdesc=""
url=""
pkgver=0.0.0-1
timestamp=1970-01-01T00:00Z
section="devel"
maintainer="Nobody <nobody@example.com>"
license=MIT
source=("https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-1.0.20200827.tar.xz")
sha256sums=(51bc85e33a5b3cf353786ae64b0f1216d7a871447f058b6137f793eb0f53b7fd)

package() {
    return
}
```

* Make sure the `src/src/wg-quick/wg` symlink gets created in the build folder and points to `../wg`

2021-03-05 23:07 UTC, raisjn commented
while you are here, the extract also breaks on https://github.com/mrichards42/remarkable_puzzles/releases/download/v0.1.0/puzzles-source.tar.gz

```

commit 0f0fab390ecfe5ca94a02b80419e66cbe1b5ae86
Author: okay <okay@chalk>
Date:   Thu Mar 4 06:16:24 2021 -0800

    [build] don't error on files without directories

diff --git a/scripts/toltec/util.py b/scripts/toltec/util.py
index 5d65469..8c0e2e0 100644
--- a/scripts/toltec/util.py
+++ b/scripts/toltec/util.py
@@ -180,6 +180,10 @@ def _auto_extract(  # pylint:disable=too-many-arguments
         if isdir(member):
             os.makedirs(file_path, exist_ok=True)
         else:
+            basedir = os.path.dirname(file_path)
+            if not os.path.exists(basedir):
+                os.makedirs(basedir, exist_ok=True)
+
             source = extract(member)
             assert source is not None



```

2021-03-07 00:07 UTC, raisjn requested changes
x

2021-03-08 10:34 UTC, matteodelabre commented
Thanks for the report @raisjn, I included your change in the latest commit.

Updated test plan:

* Make sure all other recipes still build (make repo-local)
* Build the following recipe:

```sh
#!/usr/bin/env bash
pkgnames=(test-symlinks)
pkgdesc=""
url=""
pkgver=0.0.0-1
timestamp=1970-01-01T00:00Z
section="devel"
maintainer="Nobody <nobody@example.com>"
license=MIT
source=(
    "https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-1.0.20200827.tar.xz"
    "https://github.com/mrichards42/remarkable_puzzles/releases/download/v0.1.0/puzzles-source.tar.gz"
)
sha256sums=(
    51bc85e33a5b3cf353786ae64b0f1216d7a871447f058b6137f793eb0f53b7fd
    e6be7e83386d852878a173caca73477e794e7e80e0e2584b33d0f96ade788410
)

package() {
    return
}
```

* Check that the `src/src/wg-quick/wg` symlink gets created in the build folder and points to `../wg`
* Check that the `.github/workflows/build.yml` file and its parent directories get created

2021-03-11 00:55 UTC, raisjn approved these changes
tested the example script, made sure it breaks on current and works with PR, thanks for fixing!

2021-03-11 09:44 UTC, merged

2021-03-11 09:44 UTC, matteodelabre commented
Thanks for the review!