[innernet] wrapper for wireguard
matteodelabre/toltec pull request #350
Opened 2021-04-22 20:10 UTC by plan5

innernet helps setting up and with administration of wireguard networks.

This package currently puts config in /etc/innernet. There is a commented line in the prepare section to change this to /opt/etc/innernet.

For now, I create this PR so others can test it. innernet is available as a community package in Arch or as deb packages on the repo releases page.

2021-04-22 20:14 UTC, Eeems commented
https://github.com/tonarino/innernet/blob/6d28e7f4ab20800e30ca759727e9cfbd9d6da17c/shared/src/lib.rs#L19-L22
I'd suggest that all of these should be moved under `/opt` to play nice with OS upgrades.

2021-04-22 21:38 UTC, plan5 commented
> https://github.com/tonarino/innernet/blob/6d28e7f4ab20800e30ca759727e9cfbd9d6da17c/shared/src/lib.rs#L19-L22
> I'd suggest that all of these should be moved under `/opt` to play nice with OS upgrades.

Done. Does the wireguard package keep its configs in /etc though?

2021-04-22 21:39 UTC, Eeems commented
> Done. Does the wireguard package keep its configs in /etc though?

Not if you modify that.

2021-04-23 07:25 UTC, plan5 commented
> > Done. Does the wireguard package keep its configs in /etc though?
> 
> Not if you modify that.

Ok, I've changed it for the innernet configs but not for wireguard because that would have to be done in the wireguard package first.

I'll also have to add installation of a service file

2021-04-23 11:09 UTC, plan5 commented
@Eeems Since the wireguard package still has its configs in /etc/, I'll only change the location of the innernet files for now.

Should I write an issue for wireguard to change its config location before we move on with this package?

2021-04-23 14:31 UTC, Eeems commented
> Ok, I've changed it for the innernet configs but not for wireguard because that would have to be done in the wireguard package first.
> 
> I'll also have to add installation of a service file

> @Eeems Since the wireguard package still has its configs in /etc/, I'll only change the location of the innernet files for now.
> 
> Should I write an issue for wireguard to change its config location before we move on with this package?



Sorry I was dealing with a headache while I wrote that reply. Didn't even realize I had sent it. Wireguard is still likely using `/etc` which is something we probably should patch in a different PR.

2021-04-23 14:44 UTC, Eeems commented on package/innernet/package
> +    #sed -i "s/\/etc\/wireguard/\/opt\/etc\/wireguard/g"  "$srcdir/shared/src/lib.rs"
```suggestion
    # Change config folders to live under /opt
    sed -i "s/\/etc\/innernet/\/opt\/etc\/innernet/g" "$srcdir/shared/src/lib.rs"
    sed -i "s/\/var\/lib\/innernet/\/opt\/etc\/innernet/g" "$srcdir/shared/src/lib.rs"

    #Change binary path in service file
    sed -i "s/\/usr\/bin\/innernet/\/opt\/bin\/innernet/g" "$srcdir/client/innernet@.service"

    #tbd: change wireguard config dir to /opt/etc/wireguard?
    #sed -i "s/\/etc\/wireguard/\/opt\/etc\/wireguard/g" "$srcdir/shared/src/lib.rs"
```

2021-04-23 16:24 UTC, plan5 commented
> > Ok, I've changed it for the innernet configs but not for wireguard because that would have to be done in the wireguard package first.
> > I'll also have to add installation of a service file
> 
> > @Eeems Since the wireguard package still has its configs in /etc/, I'll only change the location of the innernet files for now.
> > Should I write an issue for wireguard to change its config location before we move on with this package?
> 
> Sorry I was dealing with a headache while I wrote that reply. Didn't even realize I had sent it. Wireguard is still likely using `/etc` which is something we probably should patch in a different PR.

No problem :) I was just a bit confused. Get well!

2021-04-23 18:09 UTC, Eeems commented
Testing on the rM1 and it looks like you haven't put in the shorthand for `innernet` (`inn`). Could you add that symlink as well?

2021-04-23 21:29 UTC, plan5 commented
> Testing on the rM1 and it looks like you haven't put in the shorthand for `innernet` (`inn`). Could you add that symlink as well?
> 
> Other than that it works!

Done! I've added the link.

Also nice to hear it works for you! :) I'm having problems pinging between peers but I guess that's a server misconfig then. Befor your post I didn't know if it's because of the package.

Would be interesting to know if it works for someone else with rM2 though...

2021-04-23 21:42 UTC, Eeems commented
> Also nice to hear it works for you! :) I'm having problems pinging between peers but I guess that's a server misconfig then. Befor your post I didn't know if it's because of the package.
> 
> Would be interesting to know if it works for someone else with rM2 though...

@danshick or @raisjn would you be able to test? You'll need to go through setting up a innernet server to test with as well. If you need help with that feel free to ping me, or ask on the innernet discord: https://discord.gg/fs2nqxWKhx


> Done! I've added the link.

Awesome, I'll test that sometime soon.

2021-04-23 21:55 UTC, danshick commented
I should be able to give it a shot along with your oxide PRs tonight.

2021-04-27 02:53 UTC, mcginty commented
Author of innernet here! I'm happy to add a CLI option in the next release to override the default config and data directories so you don't have to maintain patches.

2021-04-27 02:55 UTC, danshick commented
> Author of innernet here! I'm happy to add a CLI option in the next release to override the default config and data directories so you don't have to maintain patches.

That'd be great! Thanks for your work.

2021-05-03 02:21 UTC, Eeems commented
Alright, so I can confirm that the link for `inn` works, but I've encountered an issue. Since I've rebooted my device, innernet is failing to start
![image](https://user-images.githubusercontent.com/1176979/116836244-06ea0e80-ab83-11eb-85fb-43e13ad35678.png)

@mcginty any ideas how I can get more information out of this error?

2021-05-04 02:59 UTC, mcginty commented
@Eeems hmm, I need to add better error messages! If you run `inn up eeems` manually, that has the same issue I assume? Is the wireguard kernel module loaded properly (`lsmod | grep wireguard`)?

2021-05-04 03:02 UTC, Eeems commented
Correct it does give the same error message. I forgot to check the kernel module to make sure it was loaded. Likely I forgot to add it to anything to handle it automatically loading on startup. I'll check again tomorrow and let you know.

2021-05-04 19:18 UTC, Eeems commented
@mcginty Okay, tried again and it is still failing after confirming that wireguard is loaded: 
![image](https://user-images.githubusercontent.com/1176979/117057830-23995a00-acdb-11eb-98ec-1d64a834a2cd.png)

2021-05-05 18:19 UTC, plan5 commented
It's working over reboots for me on rM2. 
Just adding for documentation's sake. 
Could this be related to rM1 exclusively?

2021-05-05 19:00 UTC, Eeems commented
> It's working over reboots for me on rM2.
> Just adding for documentation's sake.
> Could this be related to rM1 exclusively?

Potentially, since the rM1 loads wireguard from a different location, see https://github.com/toltec-dev/toltec/blob/stable/package/wireguard/package#L26-L29

2021-05-09 12:38 UTC, mcginty commented
I added more logging in [v1.3.0-beta.3](https://github.com/tonarino/innernet/releases/tag/v1.3.0-beta.3) that should hopefully help with debugging the issue on this platform. Maybe give that a shot?

2021-05-11 07:54 UTC, plan5 commented
should we maybe push this to beta.4?

@mcginty is the additional loggin only available in beta.3 or also in beta.4?
I guess that decides it.

2021-05-12 17:52 UTC, Eeems commented
![image](https://user-images.githubusercontent.com/1176979/118021233-3d105680-b318-11eb-99f1-ad5390116a60.png)
Alright this is interesting, how did `/opt/var/lib/innernet` get removed? Upon creating the directory it works fine.
![image](https://user-images.githubusercontent.com/1176979/118021394-6d57f500-b318-11eb-9515-9c10bc413c5f.png)
So for now the package should ensure the folder exists on configure. I'll open an issue with innernet itself to get it created.

2021-05-12 17:56 UTC, Eeems commented on package/innernet/package
> +}
```suggestion
}

configure() {
    if ! [ -d /opt/var/lib/innernet ]; then
        mkdir -p /opt/var/lib/innernet
    fi
}
```

2021-05-12 17:58 UTC, Eeems requested changes
Ensure that the data directory (`/opt/lib/innernet`) exists on install/upgrade.

2021-05-17 14:46 UTC, Eeems approved these changes

2021-05-17 14:47 UTC, merged