Add /opt/etc directory to xochitl oxide application
matteodelabre/toltec pull request #495
Opened 2021-11-19 15:46 UTC by murchu27

This directory needs to be visible for rM2 users who have a custom `/opt/etc/rm2fb.conf` - usually due to running a tablet version that rm2fb that does not support yet.

See Eeems/oxide#231. Originally fixes Eeems/oxide#228.

2021-11-19 16:13 UTC, Eeems submitted a review, later dismissed
lgtm. Anybody with a rm2 want to test?

2021-11-19 17:23 UTC, matteodelabre commented
I can take a look at it tonight.

2021-11-20 23:37 UTC, matteodelabre commented
@Eeems Is there a way to allow access to a single file rather than a whole directory? Allowing access to the whole `/opt/etc` directory just for one file seems too wide. Not a blocker if it’s not possible, though.

Also, I think we also allow access to the other locations the rm2fb.conf file can be read from, namely `/usr/share`, `/opt/share`, and `/etc`.

2021-11-21 00:02 UTC, Eeems commented
It uses bind mounts, which can work, but it can have some issues iirc. Like it doesn't like if the file doesn't exist.

2021-11-22 16:12 UTC, Eeems commented
> Also, I think we should also allow access to the other locations the rm2fb.conf file can be read from, namely `/usr/share`, `/opt/share`, and `/etc`.

Only if we document that users should place it there. I think if we just document `/opt/etc` it should be fine. `/etc` and `/usr/share` are already part of the list, so we would only be talking about `/opt/share` which really shouldn't be edited by users and only populated by packages.

2021-11-22 16:20 UTC, Eeems approved these changes

2021-11-22 16:21 UTC, Eeems requested changes
Looks like `/opt/etc/xochitl.env.d` is missing from the new version.

2021-11-22 16:22 UTC, Eeems approved these changes
Oh I see, it was replaced by `/opt/etc`

2021-11-22 16:22 UTC, merged