rMscreens
matteodelabre/toltec pull request #571
Opened 2022-03-15 01:14 UTC by pr0fsmith

rMscreens is a commandline utility that allows you to easily change your rM screen (sleep screen, power off screen etc).  It can also be used to backup and restore your original screens easily.

I wrote this code myself and tested it on the rM2 software version 2.12

`#! /bin/bash

#Backup existing screens: changescr -b
#Change Screen: changescrn -c [SCREEN] -n [PATH TO NEW SCREEN]
#Restore original screens: changescrn -r [SCREEN] (use option 'all' to restore all screens at once)
#[SCREEN] options: batteryempty | lowbattery | overheating | poweroff | rebooting | recovery | splash | starting | suspended 

while getopts "r: c: n: :b" opt; do
	case $opt in
		r) #Restores original screen
			case $OPTARG in 
				batteryempty | lowbattery | overheating | poweroff | rebooting | recovery | splash | starting | suspended)
					echo "restoring $OPTARG.png..."
					cp /usr/share/remarkable/backupscrns/$OPTARG.png /usr/share/remarkable >&2
					echo "Done!"
					;;
				all)
					echo "Restoring all screens..."
					cp /usr/share/remarkable/backupscrns/*.png /usr/share/remarkable
					echo "Done!"
					;;
				*)
					echo "Screen Options: batteryempty lowbattery overheating poweroff rebooting recovery splash starting suspended"
					exit 1
					;;
			esac	
			;;

		c) #Specifies which screen to change. Must be used in combination with -n
			SCREEN=$OPTARG
		   case $NEWSCRN in 
		   		"") echo "Please specify location of new screen" 
					echo "Usage: changescrn -c [SCREEN] -n [PATH TO NEW SCREEN]"
					;;
			esac
		   ;;

		n) #Specifies location of new screen.  Must be used in combination with -c
			NEWSCRN=$OPTARG
		   case $SCREEN in 
		   		batteryempty | lowbattery | overheating | poweroff | rebooting | recovery | splash | starting | suspended)
				cp $NEWSCRN /usr/share/remarkable/$SCREEN.png
				;;
    	     	*)
    	     	echo "You either didn't specify a screen option first or didn't specify a correct screen option"
    	     	echo "Usage: changescrn -c [SCREEN] -n [PATH TO NEW SCREEN]"
    	     	echo "[SCREEN] options: batteryempty | lowbattery | overheating | poweroff | rebooting | recovery | splash | starting | suspended"
    	     	;;
    	     esac
    	   
		   ;;	
		b) #Creates a backup of original screens
			mkdir /usr/share/remarkable/backupscrns
			cp /usr/share/remarkable/*.png /usr/share/remarkable/backupscrns
		   ;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires and argument." >&2
			echo "Usage: changescrn -c [SCREEN] -n [PATH TO NEW SCREEN]"
			exit 1
			;;
	esac

	
done
`

2022-03-18 16:30 UTC, Eeems commented
I would really recommend adding help output to the script.

I don't think we can merge this until https://github.com/pr0fsmith/rMscreens/issues/2 is resolved though.

2022-03-18 17:16 UTC, Eeems requested changes
Move backup location off of root partition

2022-07-06 03:26 UTC, Eeems commented
@pr0fsmith did you have a chance to address the requested changes?

2022-07-06 15:02 UTC, pr0fsmith commented
> @pr0fsmith did you have a chance to address the requested changes?

I will do that today.

2022-07-06 21:24 UTC, pr0fsmith commented
@Eeems All changes have been made.

2022-07-06 21:45 UTC, Eeems commented
@pr0fsmith I don't see any changes to this PR? Did you intend to update the source and sha256sum in the package file to pull in the latest changes?

2022-07-06 22:38 UTC, pr0fsmith commented
> @pr0fsmith I don't see any changes to this PR? Did you intend to update the source and sha256sum in the package file to pull in the latest changes?

@Eeems I actually didn't make any changes. It seems as though I made the changes months ago so the existing source should be fine.

2022-07-06 22:44 UTC, Eeems commented
@pr0fsmith it looks like this is still pointing at an old commit and doesn't have the changes that were requested.

2022-09-26 14:57 UTC, Eeems commented
@pr0fsmith poke

2022-09-26 15:04 UTC, pr0fsmith commented
I want to but I honestly dont understand how. I find the whole process confusing.

Sept 26, 2022 10:57:48 a.m. Nathaniel van Diepen ***@***.***>:

> @pr0fsmith[https://github.com/pr0fsmith] poke
> 
> —
> Reply to this email directly, view it on GitHub[https://github.com/toltec-dev/toltec/pull/571#issuecomment-1258167387], or unsubscribe[https://github.com/notifications/unsubscribe-auth/AM5FBGDMLBTMCII7ERDT6STWAG2WZANCNFSM5QXGBEYA].
> You are receiving this because you were mentioned.[Tracking image][https://github.com/notifications/beacon/AM5FBGE4MJ4U3C4D37BGVELWAG2WZA5CNFSM5QXGBEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOJL7BYWY.gif]
>

2022-09-26 15:10 UTC, Eeems requested changes

2022-09-26 15:10 UTC, Eeems commented on package/rmscreens/package
> +sha256sums=(7ecf9c5355a5f06a3424fe24b04e94fc458b93b83ca015e5700308f683d8c102)
```suggestion
source=(https://github.com/pr0fsmith/rMscreens/archive/47c01faf51cbb8dd6a83c5a26e646ae246ee26f6.zip)
sha256sums=(49cb4c57556ed807d6de613c63874f1253e54989f0445439a06158abd8514bc3)
```

2022-09-26 15:12 UTC, Eeems commented
@pr0fsmith I've added a comment showing what needs to be changed. There is a button to directly apply the suggested changes.

Updates to your repository don't automatically show up here as we point at specific commits so that we know that the source doesn't change between builds. Whenever you update your repository you need to point the recipie at the new commit.

2022-09-26 15:19 UTC, pr0fsmith commented
I don't understand how to change the recipe. You did it for me last time.

2022-09-26 15:19 UTC, Eeems commented
> I don't understand how to change the recipe. You did it for me last time.

If you go to the files changed tab, you'll see the recipie there. It's the `package/rmscreens/package` file.

2022-10-01 17:32 UTC, Eeems commented
@pr0fsmith I can't get this to work, there is no help output. When looking at the comment in the script saying how to use it, that doesn't work. It looks like your argument parsing has a loop where it will never work as both -c and -n expect the other setting to already be set.
![image](https://user-images.githubusercontent.com/1176979/193421259-208a48f1-1c5e-4f78-93b0-b21b72658b7a.png)

2023-05-08 23:38 UTC, Eeems commented
@pr0fsmith any chance you could get this cleaned up and ready? I'd love to get it merged.

2023-08-15 23:49 UTC, Eeems approved these changes

2023-08-15 23:50 UTC, Eeems commented
It would be nice to have this automatically do a backup/restore on install, but we'd need a better mechanism to make sure that normal usage can't interfere with what files are backed up or restored.

2023-08-15 23:51 UTC, merged