Stracciatella kernel
matteodelabre/toltec pull request #582
Opened 2022-04-02 17:34 UTC by Etn40ff

This is my take on the default kernel for both rm1 and rm2.

Sources are exactly those provided by RemarkableAS.

Configs differs from theirs as follows:

Removed version name modifications
TRIM_UNUSED_KSYMS=n
UINPUT=y
TUN=y
It requeres kernelctl and it should be a safe kernel to test its
functionalities.

2022-04-04 02:00 UTC, gbyl requested changes

2022-04-04 02:00 UTC, gbyl commented on package/linux-stracciatella/package
> +pkgdesc="RemarkableAS's vanilla kernel with few extra flakes"
```suggestion
pkgdesc="RemarkableAS's vanilla kernel with a few extra flakes"
```

2022-04-04 02:00 UTC, gbyl commented on package/linux-stracciatella/package
> +    echo -e "Please kernelctl to select the kernel to boot."
```suggestion
    echo -e "Please use kernelctl to select the kernel to boot."
```

2022-08-02 08:06 UTC, Etn40ff commented
This kernel requires firmware blobs that were introduced in version 2.9. Now we print a warning when installing on an older version.

2022-08-02 23:12 UTC, luvanir commented
RM1 owner here. linux-stracciatella works wonders! The only caveat is that you need to have at least version 2.9 of the remarkable OS before you switch away from the vanilla kernel. Dear maintainers, let me know if there are any tests you would like me to run before merging. Thank you for the help troubleshooting, Salvatore.

2022-09-26 14:56 UTC, Eeems commented
@Etn40ff did you test this on a rM2?

2022-09-26 16:02 UTC, Eeems commented
Tested on my rM1 as well and this works. I'd like someone to confirm that they tested on a rM2 and that it works.

2022-09-26 16:20 UTC, Etn40ff commented
> @Etn40ff did you test this on a rM2?

It has been my daily drive since April.

2022-09-26 16:28 UTC, Eeems approved these changes

2022-09-26 16:28 UTC, merged