Bump ddvk 2.13.0.758
matteodelabre/toltec pull request #593
Opened 2022-06-06 09:09 UTC by Etn40ff

This bumps ddvk's hacks to rm1: 2.12.3.606 and rm2: 2.13.0.758.

For rm1 version 32.1.02 has been superseeded by 32.1.3.

I am still on 2.12.3.606 so I can't test this PR.

2022-06-06 12:43 UTC, EntrixIII commented
Doesn't build, Invalid checksum.
```
toltec.builder.BuildError: Invalid checksum for source file https://github.com/ddvk/remarkable-hacks/archive/408694677aba3607aa8ee56bc0368baf91568ce7.zip:
  expected ie821c99751f12c65137d5c5dc3387b6663123cf03e1551b5af970ef4290fad5a
  actual   e821c99751f12c65137d5c5dc3387b6663123cf03e1551b5af970ef4290fad5a
```
Seems like you forgot an `i`.

2022-06-06 12:50 UTC, Etn40ff commented
Oops

2022-06-06 12:53 UTC, EntrixIII requested changes
an `i` too much and possibly wrong directory, because it doesnt seem to build for rm2 either

2022-06-06 12:53 UTC, EntrixIII commented on package/ddvk-hacks/package
> +sha256sums=(ie821c99751f12c65137d5c5dc3387b6663123cf03e1551b5af970ef4290fad5a)
Has an `i` it shouldn't have

2022-06-06 12:53 UTC, EntrixIII commented on package/ddvk-hacks/package
> +        install -D -m 644 -t "$pkgdir$_patches_dir" "$srcdir"/patches/2123606_rm2/patch_33.2.01
You didn't change the directory name, it should probably be `2130758_rm2` instead of `2123606_rm2`

2022-06-06 14:01 UTC, Etn40ff commented
Sorry for the mess, I made the PR without access to my build system. It should be fine now.

2022-06-10 22:16 UTC, matteodelabre approved these changes
Tested on rM2, version 2.13.0.758. Thanks for the PR!

2022-06-10 22:26 UTC, merged