package/linux-mainline: Bump to 5.19
matteodelabre/toltec pull request #610
Opened 2022-08-01 07:47 UTC by alistair23

Bump from the 5.18 to the 5.19 kernel. No rM2 specific changes here, just keeping up to date with the Linux kernel

2022-08-10 00:03 UTC, gbyl requested changes

2022-08-10 00:03 UTC, gbyl commented on package/linux-mainline/package
> +pkgver=5.19.0-0
```suggestion
pkgver=5.19.0-1
```

toltec package [revision versions](https://github.com/toltec-dev/build/blob/main/docs/recipe-format.md#pkgver-field) start at 1

2022-08-10 20:22 UTC, Etn40ff commented
Could you please also change the commands to package the resulting kernel from 
```
tar --owner root:0 --group root:0 --mtime=$timestamp \
    -cjf "$pkgdir"/opt/usr/share/kernelctl/"$archive" -C "$staging" .
```
to
```
(cd "$staging" && tar --owner root:0 --group root:0 --mtime=$timestamp \
    -cjf "$pkgdir"/opt/usr/share/kernelctl/"$archive" boot/* lib/modules/*)
```

2022-08-19 17:00 UTC, Etn40ff commented
LGTM

2022-09-07 11:57 UTC, alistair23 commented
Ping!

2022-09-24 22:08 UTC, alistair23 commented
Ping!

2022-09-26 14:55 UTC, Eeems commented
@Etn40ff Did you test this on device?

2022-09-26 16:26 UTC, Etn40ff commented
> @Etn40ff Did you test this on device?

Yes, back in August after the changes I asked for. If I remember correctly it worked as expected.

2022-09-26 19:27 UTC, Eeems commented
@Etn40ff can you do a quick test on device since we've changed the package. I just need to know the following:

- Install works fine and has the expected output
- Using kernelctl to change the kernel to this, and then to something else works
- Uninstall works fine

2022-09-26 21:11 UTC, Etn40ff commented
All seems to be fine on my end. One last change that needs to happen is that `postremove` must be deleted. Other than that it has my green light.

2022-09-26 21:49 UTC, Etn40ff commented
Tested again. LGTM

2022-09-26 21:54 UTC, Eeems approved these changes

2022-09-26 21:54 UTC, merged