Merge/2022 w34
matteodelabre/toltec pull request #619
Opened 2022-08-21 18:08 UTC by Eeems

### New Packages

- `rmfm` - 1.4.0-1 (#608 #617)
- `ripgrep` - 13.0.0-1 (#611)
- `lf` - r27-1 (#612)

### Updated Packages

- `yaft` - 0.0.7-1 (#613)
  - Fix input on rM1
  - Update to 0.0.7

2022-08-21 18:58 UTC, LinusCDE requested changes
Tested on rM 2.

**rmfm** starts fine from ssh, but **does nothing when launched through remux**.

```
Aug 21 20:29:21 reMarkable remux[8136]: env: can't execute 'node': No such file or directory
```

Given that node exists at `/opt/bin/node` I would guess that remux is missing or not transferring a PATH variable containing `/opt/bin`.

A quick temporary fix is to change/patch the shebang in `/opt/bin/rmfm`:
```diff
-#!/usr/bin/env node
+#!/opt/bin/node
```

For the long term, this should probably be adressed in remux (@raisjn).

Launching the app failes anyway though. I'm not sure here, but maybe node expects a full tty?

```
Aug 21 20:57:59 reMarkable remux[614]: /opt/bin/rmfm:52
Aug 21 20:57:59 reMarkable remux[614]:   output = output.stdout.toString().trim();
Aug 21 20:57:59 reMarkable remux[614]:                          ^
Aug 21 20:57:59 reMarkable remux[614]: TypeError: Cannot read property 'toString' of null
Aug 21 20:57:59 reMarkable remux[614]:     at ls (/opt/bin/rmfm:52:26)
Aug 21 20:57:59 reMarkable remux[614]:     at Object.<anonymous> (/opt/bin/rmfm:402:1)
Aug 21 20:57:59 reMarkable remux[614]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
Aug 21 20:57:59 reMarkable remux[614]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Aug 21 20:57:59 reMarkable remux[614]:     at Module.load (internal/modules/cjs/loader.js:950:32)
Aug 21 20:57:59 reMarkable remux[614]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Aug 21 20:57:59 reMarkable remux[614]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Aug 21 20:57:59 reMarkable remux[614]:     at internal/main/run_main_module.js:17:47
```

Edit: The above issue seems to have the same root cause. `output` refers to running `simple` which is most likely not in `$PATH` either.

2022-08-21 19:03 UTC, Eeems commented
@LinusCDE could you make the rmfm package maintainer aware of the issues you found?

2022-08-21 19:11 UTC, LinusCDE commented
The thing is, I'm not sure if this is on the project maintainer to actually fix. His implementation is totally okay.

This should be fixed in remux, as apps launched from opkg should have access to the paths in `/opt`.

I tested a little, and it would probably be the easiest to add a patch for the rmfm package until it is fixed in remux.

With this, remux can launch rmfm fine:
```diff
-#!/usr/bin/env node
+#!/opt/bin/node
+process.env.PATH += ":/opt/bin"
```

2022-08-21 19:14 UTC, LinusCDE commented
I'm creating a PR for patching this in as well as an issue for remux.

2022-08-21 20:16 UTC, LinusCDE commented
Hotfix is created and tested to be working: https://github.com/toltec-dev/toltec/pull/620

Including this here will fix rmfm for remux.

New remux issue: https://github.com/rmkit-dev/rmkit/issues/177

2022-08-22 15:18 UTC, LinusCDE approved these changes
From my point of view, this should be good to go then.

Since I reviewed the oxide changes, I would consider them to be fine as well.

2022-09-26 16:53 UTC, merged