tailscale-systemd package
matteodelabre/toltec pull request #706
Opened 2023-07-12 06:37 UTC by kiwiz

*What*
A package with the necessary systemd service configuration to get Tailscale working on rM devices. Requires the base `tailscale` package.

*Authorship*
Service file comes directly from https://remarkable.guide/tailscale.html

*Specificity*
Should work on all

2023-07-12 06:58 UTC, Eeems requested changes

2023-07-12 06:58 UTC, Eeems commented on package/tailscale-systemd/package
> +    install -D -m 644 -t "$srcdir"/tailscaled.service /lib/systemd/system/tailscaled.service
We've been putting service files under `/etc/systemd/system` as a rule in toltec.

2023-07-12 06:58 UTC, Eeems commented on package/tailscale-systemd/tailscaled.service
> +ExecStart=/opt/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-liste
Try to place things under `/opt` if possible. So `/var/lib/tailscale/tailscaled.state` should be `/opt/var/lib/tailscale/tailscaled.state`. it's fine to use `/run` as it's tmpfs.

2023-07-13 02:27 UTC, kiwiz commented
* [ ] Test on device

2023-07-13 04:16 UTC, kiwiz commented
Having trouble running `toltecmk` on my host. Looks like it might be due to https://github.com/toltec-dev/build/pull/31, but I don't see anything that would be interpretted as a C-quoted string.

2023-07-13 04:30 UTC, Eeems commented
> Having trouble running `toltecmk` on my host. Looks like it might be due to [toltec-dev/build#31](https://github.com/toltec-dev/build/pull/31), but I don't see anything that would be interpretted as a C-quoted string.

It's based on the version of bash you are using underneath or something IIRC, so you won't see it in your package recipe.

2023-07-13 04:31 UTC, Eeems commented on package/tailscale-systemd/package
> +# SPDX-License-Identifier: BSD-3-Clause
This is the license for this file, not the underlying software it's packaging. It must be MIT.

2023-07-14 19:07 UTC, kiwiz commented
Tested on my rm2. Install + usage works fine. However, `is-active` and `is-enabled` are undefined when uninstalling. Do those need to be sourced somehow?

2023-07-14 19:38 UTC, Eeems commented
> Tested on my rm2. Install + usage works fine. However, `is-active` and `is-enabled` are undefined when uninstalling. Do those need to be sourced somehow?

When built through toltec, install-lib is available, but toltecmk doesn't include it.

I work around that when building with toltecmk by embedding them when a package isn't part of the main toltec workflow: https://github.com/Eeems-Org/oxide/blob/master/package#L17-L53

2023-07-15 02:30 UTC, kiwiz commented
Ack. Tested locally with the relevant functions and it looks good.

2023-07-15 02:32 UTC, Eeems commented
> Ack. Tested locally with the relevant functions and it looks good.

Have you tested with the packages generated by the actions on this PR?

2023-07-15 02:33 UTC, kiwiz commented
Oh, I have not! Will do that now.

2023-07-15 02:38 UTC, kiwiz commented
Confirmed that:
1) Package installs
2) Tailscaled comes up
3) Uninstall cleans up service

2023-07-15 02:45 UTC, Eeems approved these changes
I haven't tested anything as I'm not setup to be able to test tailscale at all, but if it works for you that's good enough for me right now.

2023-07-15 02:45 UTC, merged