package/linux-mainline: Bump to 6.3
matteodelabre/toltec pull request #732
Opened 2023-08-28 09:12 UTC by alistair23

Bump to the 6.3 kernel and update the list of issues

2023-08-28 15:44 UTC, Eeems commented
For the otg control, are you planning on importing the remarkable pogo modules in the future?

2023-08-28 22:49 UTC, alistair23 commented
I'm not currently planning on it, I have no interest in it and I feel it will be difficult to upstream. If someone else wanted to they are welcome to though

2023-08-28 23:12 UTC, Eeems commented
> I'm not currently planning on it, I have no interest in it and I feel it will be difficult to upstream. If someone else wanted to they are welcome to though

There wouldn't be too much of a need to upstream it to be honest, it would be simple enough to just add to the kernel we ship in toltec.

2023-12-06 02:19 UTC, Eeems commented
@alistair23 sorry for how long this is taking. I don't have a rM2 to test with, and I'm waiting on the other maintainers to do so.

2024-01-06 03:24 UTC, Eeems commented on package/linux-mainline/package
>  timestamp=2022-05-22T21:50:09Z
I just noticed that the timestamp wasn't updated

2024-05-20 23:23 UTC, Eeems commented
I have a rM2 to test with now, although I don't have the parts for recovery quite yet. That said, I'll probably still be able to test.

2024-05-21 00:39 UTC, Eeems requested changes
The package is missing the installdepends on kernelctl.

2024-05-21 00:49 UTC, jkesselm commented
If I'd known you didn't, I'd have been persuadable to lend mine...

--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

Caveat: Opinionated old geezer with overcompensated writer's block. May be redundant, verbose, prolix, sesquipedalian, didactic, officious, or redundant.
________________________________
From: Nathaniel van Diepen ***@***.***>
Sent: Monday, May 20, 2024 7:23:45 PM
To: toltec-dev/toltec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [toltec-dev/toltec] package/linux-mainline: Bump to 6.3 (PR #732)


I have a rM2 to test with now, although I don't have the parts for recovery quite yet. That said, I'll probably still be able to test.

—
Reply to this email directly, view it on GitHub<https://github.com/toltec-dev/toltec/pull/732#issuecomment-2121385320>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7OJ6W3V3ENDVIFYG2Q73KDZDKAYDAVCNFSM6AAAAAA4BDQAC2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRRGM4DKMZSGA>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-05-24 07:51 UTC, Etn40ff commented
6.3 works on 2.15 but 6.2 no. 

```
reMarkable: ~/ cd /tmp/
reMarkable: /tmp/ tar xf /tmp/linux-mainline_6.3.0-1_rm2.ipk 
reMarkable: /tmp/ tar xf /tmp/data.tar.gz 
reMarkable: /tmp/ tar xf ./opt/usr/share/kernelctl/mainline-6.3.0.tar.bz2
reMarkable: /tmp/ cp -r /tmp/lib/modules/6.3.0/ /lib/modules/
reMarkable: /tmp/ kexec -l /tmp/boot/zImage --command-line="console=ttymxc0,115200 root=/dev/mmcblk2p2 rootwait rootfstype=ext4 rw quiet panic=20 systemd.crash_reboot systemd.show_status=0 loglevel=0 crashkernel=32M" --dtb=/tmp/boot/zero-sugar.dtb 
reMarkable: /tmp/ /bin/sync
reMarkable: /tmp/ systemctl kexec
```

2024-05-24 17:03 UTC, Eeems commented
I'll have to test on 3.3 to confirm that it works there as well, and then adjust the package recipe to allow it in os3 again.

2024-05-27 11:17 UTC, alistair23 commented
> The package is missing the installdepends on kernelctl.

Thanks for adding it!

2024-06-05 21:12 UTC, Eeems commented
Works on 2.15 with expected issues. Next will be to test on 3.3 with the folio.

2024-06-05 21:24 UTC, Eeems commented
Okay, this works on 3.3, I'll update the PR to have it no longer be removed and to add the note that the folio doesn't work (as it doesn't).

2024-06-05 21:33 UTC, Eeems approved these changes

2024-06-05 21:56 UTC, merged