Update toltecctl to fix uninstalling error
matteodelabre/toltec pull request #740
Opened 2023-09-14 18:23 UTC by Jayy001

This fixes
```
reMarkable: ~/ toltecctl uninstall
This will wipe out all files in '/opt'. Continue? [y/N] y
2023-09-13 18:53:42 URL:https://bin.entware.net/armv7sf-k3.2/installer/opkg [752476/752476] -> "/home/root/.local/bin/opkg" [1]
Removing package autoconf from root...
Refusing to remove essential package busybox.
    Removing an essential package may lead to an unusable system, but if
    you enjoy that kind of pain, you can force opkg to proceed against
    its will with the option: --force-removal-of-essential-packages
```

2023-09-17 18:45 UTC, Eeems requested changes
This doesn't resolve the issue for uninstall, it looks like you updated the reenable logic instead of the uninstall logic.

2023-09-18 15:35 UTC, Jayy001 commented
Yeup, fixed

2023-09-18 17:41 UTC, Eeems commented
I'll try to get this tested and approved later this week. I'm busy the next two days.

2023-09-25 17:42 UTC, Eeems approved these changes

2023-09-25 18:20 UTC, merged