Update webinterface-wifi to v2.0.0
matteodelabre/toltec pull request #768
Opened 2023-12-06 16:58 UTC by rM-self-serve

[Release Notes v2.0.0](https://github.com/rM-self-serve/webinterface-wifi/releases/tag/v2.0.0)
[Docs](https://github.com/rM-self-serve/webinterface-wifi)

Quite a bit of new functionality. For anyone testing this, there are [test ssl certs in the repository](https://github.com/toltec-dev/toltec/pull/github.com/rM-self-serve/webinterface-wifi/tree/master/ssl_test_cert).

Should work on all devices+versions.

2023-12-06 20:42 UTC, Eeems requested changes
Upon testing, trying to enable the service doesn't work as it's trying to run `/opt/bin/webinterface-wifi --run 80` which is no longer valid.

It may also be worth adding some more helpful output to `configure()` to point the user in the right direction for configuring it?

2023-12-07 01:39 UTC, rM-self-serve commented
Sorry for that oversight, the correct service file should now be installed.  

I mentioned where to find usage and docs locally and remotely.

Thanks for testing! I was not aware of the release window so my apologies for cutting it so close.

2023-12-07 01:41 UTC, Eeems commented
> Sorry for that oversight, the correct service file should now be installed.
> 
> I mentioned where to find usage and docs locally and remotely.

No worries, this is why we test :stuck_out_tongue: 

> 
> Thanks for testing! I was not aware of the release window so my apologies for cutting it so close.

No worries about the release window. I just picked the earlier one as I don't have to rely on another maintainer to test this.

2023-12-07 03:33 UTC, Eeems commented on package/webinterface-wifi/package
> -    how-to-enable "$pkgname.service"
I think it's still worth leaving this in as it's standard output for toltec.

2023-12-07 17:01 UTC, rM-self-serve commented
Sounds good to me!

2023-12-07 20:24 UTC, Eeems commented
Okay, testing this, and I realized it doesn't automatically restart the service if it's already enabled and running. Since this isn't a launcher which could have various applications running in an unsaved state, it should be safe to restart the service.

```bash
if is-active webinterface-wifi.service; then
    systemctl restart webinterface-wifi
fi
```

2023-12-08 01:28 UTC, Eeems approved these changes

2023-12-08 01:28 UTC, merged