Pin specific versions of Folly's clang deps
matteodelabre/toltec pull request #823
Opened 2024-01-09 05:14 UTC by bkirwi

While poking at https://github.com/bkirwi/folly/issues/2, I noticed that Ubuntu ships multiple versioned packages of `clang`, so it's actually relatively straightforward to switch back to a compatible version.

I'll still work to get a version of the ML runtime that's compatible with the cutting edge, so things don't bitrot forever and to justify the fairly large amount of time I've already spent, but this should unbreak things in the meantime.

2024-01-09 05:16 UTC, Eeems commented
> Ubuntu

We actually use debian as the base for the toolchain images.

2024-01-09 05:17 UTC, Eeems requested changes
You'll need to update the version number to force a rebuild. Just change it from `-3` to `-4`

2024-01-10 02:44 UTC, bkirwi commented
Updated with the requested changes!

2024-01-10 03:23 UTC, Eeems approved these changes
lgtm. I opened a couple non-blocking (and one unrelated) issues on the folly repo for you to look at eventually.

2024-01-11 02:52 UTC, merged